src/Entity/Reponse.php
<?php

namespace App\Entity;

use App\Repository\ReponseRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ReponseRepository::class)]
class Reponse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("reponse")]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"idAdmin est obligatoire")]
    #[Groups("reponse")]
    private ?string $idUser = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message:"note est obligatoire")]
    #[Assert\Length(  
        min : 10,
       minMessage:" Entrer 10 caractères au minimum"
   
        )]
        #[Groups("reponse")]
    private ?string $note = null;

  

    #[ORM\ManyToOne(inversedBy: 'reponses')]
  
    private ?Reclamation $Reclamation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups("reponse")]
    private ?\DateTimeInterface $createdAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?string
    {
        return $this->idUser;
    }

    public function setIdUser(string $idUser): self
    {
        $this->idUser = $idUser;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(string $note): self
    {
        $this->note = $note;

        return $this;
    }

   

    public function getReclamation(): ?Reclamation
    {
        return $this->Reclamation;
    }

    public function setReclamation(?Reclamation $Reclamation): self
    {
        $this->Reclamation = $Reclamation;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Controller/back/ReponseController.php
<?php

namespace App\Controller;

use App\Entity\Reponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Form\ReponseFormType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ReponseRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ReponseController extends AbstractController
{
    #[Route('/reponse', name: 'reponse')]
    public function index(ReponseRepository $reponseRepository): Response
    {
        return $this->render('reponse/reponse_index.html.twig', [
            'reponses' => $reponseRepository->findAll(),
        ]);
    }
    

     #[Route('/reponse_new', name: 'reponse_new')]
    public function new(Request $request): Response
    {
        $reponse = new Reponse();

        $form = $this->createForm(ReponseFormType::class, $reponse);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $reponse->setCreatedAt(new \DateTime('now'));
           
            $entityManager->persist($reponse);
            $entityManager->flush();

            return $this->redirectToRoute('reponse');
        }

        return $this->renderForm('reponse/new.html.twig',['form'=>$form]);
    }



    #[Route('/reponse_edit/{id}', name: 'reponse_edit')]
    public function edit(Request $request, int $id): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $reponse = $entityManager->getRepository(Reponse::class)->find($id);
        $form = $this->createForm(ReponseFormType::class, $reponse);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
           
            $reponse->setCreatedAt(new \DateTime('now'));
        
            // save the changes to the database
            $entityManager->persist($reponse);
            $entityManager->flush();
        
            return $this->redirectToRoute('reponse');
        }
        
        return $this->renderForm('reponse/new.html.twig', ['form' => $form]);
        
        
    }

    #[Route('/reponse_delete/{id}', name: 'reponse_delete')]
    public function delete(reponse $reponse, EntityManagerInterface $entityManager)
    {
        $entityManager->remove($reponse);
        $entityManager->flush();
    
        return $this->redirectToRoute('reponse');
    }

    /** PARTIE JSON */
    #[Route("repdisplayJSON", name:"reponse_displayJSON")]
    public function displayJSON(ReponseRepository $repo, NormalizerInterface $normalizer)
    {
        $reponse = $repo->findAll();
        $reponseNormalises = $normalizer->normalize($reponse, 'json', ['groups' => "reponse"]);
        $json= json_encode($reponseNormalises);
        return new Response($json);
    }

    #[Route("repaddJSON", name:"reponse_addJSON")]
    public function addJSON(Request $req, NormalizerInterface $Normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $reponse = new Reponse();
        $reponse->setIdUser(intval($req->get('IdUser') ?? 0));
        $reponse->setNote($req->get('note'));
        $createdAt = new \DateTime($req->get('createdAt'));
        $reponse->setCreatedAt($createdAt);
        $em->persist($reponse);
        $em->flush();

        $jsonContent = $Normalizer->normalize($reponse, 'json', ['groups' => 'reponse']);
        return new Response(json_encode($jsonContent));
    }

    #[Route("repeditJSON/{id}", name:"reponse_editJSON")]
    public function editJSON(Request $req, $id, NormalizerInterface $Normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $reponse = $em->getRepository(Reponse::class)->find($id);
        $reponse->setIdUser(intval($req->get('IdUser') ?? 0));
        $reponse->setNote($req->get('note') ?? '');
        $createdAt = new \DateTime($req->get('createdAt'));
        $reponse->setCreatedAt($createdAt);
        $em->flush();

        $jsonContent = $Normalizer->normalize($reponse, 'json', ['groups' => 'reponse']);
        return new Response("Reponse updated successfully" . json_encode($jsonContent));
    }

    #[Route("repdeleteJSON/{id}", name:"reponse_deleteJSON")]
    public function deleteJSON(Request $req, $id, NormalizerInterface $Normalizer)
    {
        $em = $this->getDoctrine()->getManager();
        $reponse = $em->getRepository(Reponse::class)->find($id);
        $em->remove($reponse);
        $em->flush();

        $jsonContent = $Normalizer->normalize($reponse, 'json', ['groups' => 'reponse']);
        return new Response("Reponse deleted successfully" . json_encode($jsonContent));
    }
   
}

templates/reponse/edit.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Modifier la réponse{% endblock %}

{% block body %}
<div class="row">
<div  style="display: flex;align-items: center;justify-content: center;margin-top: 80px; padding:45px; margin-left: 700px; padding:45px;   ">
<div class="card-body">


    <h1>Modifier la réponse</h1>

    {{form_start(form,{'attr': {'novalidate': 'novalidate'}} )}}

 {{ form_widget(form) }}

        <button type="submit" class="btn btn-primary" name="update_and_list">{{ 'Mettre à jour et retourner à la liste' }}</button>
    </form>
    
    {% if app.request.method == 'POST' and app.request.request.has('update_and_list') %}
        {% set redirectToPath = path('reponse') %}
        <script type="text/javascript">
            window.location.href = "{{ redirectToPath }}";
        </script>
    {% endif %}
         </div>
      </div>
       </div>
    

{% endblock %}

templates/reponse/index.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Hello ReponseController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/xampp/htdocs/AssurancePidev/src/Controller/ReponseController.php'|file_link(0) }}">src/Controller/ReponseController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/xampp/htdocs/AssurancePidev/templates/reponse/index.html.twig'|file_link(0) }}">templates/reponse/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/reponse/new.html.twig
{% extends 'base_back.html.twig' %}




{% block title %}Repondre{% endblock %}

{% block body %}
<div class="row">
  <div class="col-md-6 offset-md-3">
    <div class="card" style="margin-top: 80px; padding: 30px;">
      <div class="card-body">

    <h1>Répondre</h1>

    {{form_start(form,{'attr': {'novalidate': 'novalidate'}} )}}

<div class="form-group">
          {{ form_label(form.idUser, 'idAdmin') }}
          {{ form_widget(form.idUser, {'attr': {'class': 'form-control'}}) }}
          <div style="color:red"> {{ form_errors(form.idUser,{'attr':{'class':'text-danger'}}) }}</div>
        </div>
           </br>  

         <div class="form-group">
          {{ form_label(form.note) }}
          {{ form_widget(form.note, {'attr': {'class': 'form-control'}}) }}
           <div style="color:red"> {{ form_errors(form.note,{'attr':{'class':'text-danger'}}) }}</div>
        </div>

            </br>    
               
     <div class="form-group text-center">
          <button type="submit" class="btn btn-primary btn-lg">Envoyer</button>
        </div>
    {{ form_end(form) }}

      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/reponse/reponse_index.html.twig
{% extends 'base_back.html.twig' %}

{% block title %}Liste des réponses{% endblock %}

{% block body %}
<div class="row">
<div  style="display: flex;align-items: center;justify-content: center;margin-top: 80px; padding:45px; margin-left: 260px; padding:45px;  ">

<div class="card-body">

    <h1>Liste des réponses</h1>

<table class="table table-bordered">
  <thead>
    <tr>
       <th scope="col">idUser</th>
      <th scope="col">Date et heure </th>
     <th scope="col">Note</th>
     <th scope="col">Référence réclamation</th>
     <th scope="col">Actions</th>
    </tr>
  </thead>
    <tbody>
  {% for reponse in reponses %}

    <tr>
       <td>{{ reponse.idUser}}</td>
                   <td>{{ reponse.createdAt|date('Y-m-d     H:i')}}</td>
                    <td>{{ reponse.note }}</td>
                  <td>{{ reponse.reclamation.reference ?? 'N/A' }}</td>
                 
   
                  

                   
                    <td>
                 
                   <button class="btn btn-success" onclick="window.location.href='{{ path('reponse_edit', {'id': reponse.id}) }}'">Modifier</button>
                   

 
    <a href="{{ path('reponse_delete', {'id': reponse.id}) }}" class="btn btn-danger" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette réclamation ?')">Supprimer</a>
                    </td>
                </tr>
                  </tbody>
            {% endfor %}
        </tbody>
    </table>

   
   
  
         </div>
      </div>
    
</div>

{% endblock %}